---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ["--django"]
        exclude: ^(tests/fixtures.py|tests/server_utils.py|tests/data/)
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          - "--line-length"
          - "88"
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=88]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==22.3.0
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
  # The rest of these things are good to have, but not necessarily needed
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - "--format"
          - parsable
          - "--strict"
  # - repo: https://github.com/sirwart/ripsecrets.git
  #   # Will not work on windows
  #   rev: v0.1.4
  #   hooks:
  #     - id: ripsecrets
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.26.0
    hooks:
      - id: talisman-commit
        # This is needed cause talisman renames itself to cmd for some reason.
        # See https://stackoverflow.com/questions/68801910/ for details
        entry: cmd --githook pre-commit
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations
      - id: python-no-log-warn
      - id: python-check-blanket-type-ignore
      - id: text-unicode-replacement-char
  - repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.1.0
    hooks:
      - id: rm-unneeded-f-str
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.3
    hooks:
      - id: pycln
